version: "3.7"

services:
  hotel_api:
    container_name: hotelapi
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_HOST: db
      DB_DATABSASE: hotel
      DB_USERNAME: root
      DB_PASSWORD: root
    ports:
      - 8000:8000
    depends_on:
      - db
    volumes:
      - ./src:/app
    networks:
      - hotel_network

  db:
    container_name: hotel_database
    image: mysql:5.7.22
    restart: always
    environment:
      MYSQL_DATABASE: hotel
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 33066:3306

    networks:
      - hotel_network
networks:
  hotel_network:
